# Generated by Django 6.0.1 on 2026-01-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
        ('core_user', '0004_alter_user_created_alter_user_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_like',
            field=models.ManyToManyField(related_name='liked_by', to='core_post.post'),
        ),
    ]
