# Generated by Django 6.0.1 on 2026-02-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_user_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='post_like',
            new_name='posts_liked',
        ),
    ]
